### ISSUE TITLE
Create Project Summary

### ISSUE THREAD

**Issue by japerezg86** [japerezg86/video-game-collection-tracker#1]
A project summary should be evocative. It should capture a reader and make them want to contribute to or use your app. In this milestone you will write an executive summary that defines the goals and objectives of your project in language that is easily readable and mental-image evoking. I (or anyone else) should be able to read your executive summary and instantly know a) what the app is and b) why it is important. Summaries should be exciting and interesting. A summary does not need technical detail to describe interesting functionality. You should mention your product by name without using phrases such as “the team”, “the class”, “the instructor”, “project 2” etc.

Your summary will be the first part of your project landing page on Github.

Submission materials
You should submit a summary document (in markdown format) on your Github project repo. Call the file README.md and place it in the top-level directory of your Github project.

It should contain the following:

The executive summary
Installation
Getting Started
License

https://mlhale.github.io/CYBR8470/projects/project1.html

**Comment by CernickyR** [comment]
Project summary can be found at the base of the github repo.

**Comment by CernickyR** [comment]
This was apart of Pt. 1 submitted on Nov. 9 2020
