### ISSUE TITLE
Create additional User Stories

### ISSUE THREAD

**Issue by japerezg86** [japerezg86/video-game-collection-tracker#2]
Requirements are extremely important when building a product. Clearly understanding your users and the features that will support them helps you avoid wasting time on tangential ideas that are not core to the product.

In this milestone you will write user stories that define your project requirements.

Submission materials
The stories
For milestone 1, define the most important user stories for your product. Pay careful attention to structure the user stories as we discussed in lecture. Specifically, submit your user stories using the following template. Include them as markdown in a README.md file located within a folder called docs within your main project repository.

As a user/role, I want to goal so I can rationale.

Markdown syntax for this is as follows:

As a **user/role**, I want to **goal** so I can **rationale**.
Example 1: As a beta tester, I want to view the company forums, so I can post about my experiences in the beta.

Example 2: As an administrator, I want to moderate the forums, so I can prevent abusive behaviors and ensure policy compliance.

Example 3: As an interested buyer, I want to view public releases on the forums, so I can track the development process and learn about new product features before they release.

Acceptance criteria.
For each story, define at least one acceptance criteria. The acceptance criteria define the set of requirements that tell you when you are done with the user story.

Mis-user stories
In addition to the user stories identify the ways in which users might be able to mis-use your app. Mis-user stories are just like user stories except the user, goal, and rationale are malicious.

Mitigation Criteria
For each mis-user story identify at least one mitigation criteria. The mitigation criteria define the set of requirements that tell you when you are done protecting against the mis-user story.

**Comment by CernickyR** [comment]
User Stories can be found under docs/readme.md

**Comment by CernickyR** [comment]
This was apart of Pt. 1 submitted on Nov. 9 2020
